# Generated by Django 5.0.6 on 2024-07-08 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created']},
        ),
    ]
