# Generated by Django 5.0.6 on 2024-07-30 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_description'),
        ('todos', '0002_alter_todo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='todo_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todos.todo'),
        ),
    ]
