# Generated by Django 5.0.6 on 2024-07-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_todo_field'),
        ('todos', '0002_alter_todo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='todo_field',
        ),
        migrations.AddField(
            model_name='note',
            name='todo_field',
            field=models.ManyToManyField(blank=True, to='todos.todo'),
        ),
    ]
