# Generated by Django 5.0.6 on 2024-07-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_todo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='label',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
