# Generated by Django 5.0.6 on 2024-07-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thought',
            old_name='owner',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='thought',
            old_name='thought',
            new_name='content',
        ),
        migrations.AddField(
            model_name='thought',
            name='image',
            field=models.ImageField(blank=True, default='logo.png', null=True, upload_to=''),
        ),
    ]
