# Generated by Django 5.0.6 on 2024-07-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0003_alter_thought_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='content',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
